export default {
 SET_FROM : 'SET_FROM',
 SET_TO : 'SET_TO',
 SET_INTEREST : 'SET_INTEREST',
 SET_PRINCIPAL : 'SET_PRINCIPAL',
 SET_AMOUNTYEAR_YEAR : 'SET_AMOUNTYEAR_YEAR',
 SET_AMOUNTYEAR_VALUE : 'SET_AMOUNTYEAR_VALUE',
 ADD_AMOUNTYEAR : 'ADD_AMOUNTYEAR',
 DELETE_AMOUNTYEAR : 'DELETE_AMOUNTYEAR',
 SET_TYPE : 'SET_TYPE',
 TOGGLE_STATUS : 'TOGGLE_STATUS',
 UPDATE_DATA : 'UPDATE_DATA'
}
